name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-check]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -X PATCH -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'status=in_progress' \
            -f 'output[title]=My Check Run Title ðŸ¤”' \
            -f 'output[summary]=A *fancy* summary' \
            -f 'output[images][][image_url]=https://www.kenmuse.com/favicon/apple-touch-icon.png' \
            -f 'output[images][][caption]=Sample from kenmuse.com' \
            -f 'output[images][][alt]=Logo for kenmuse.com' \
            /repos/${{ github.repository }}/check-runs/${{ github.event.client_payload.checkRunId }}          

      - name: Processing        
        run: sleep 10

      - name: Complete Check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -X PATCH -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/check-runs/${{ github.event.client_payload.checkRunId }} \
            --input - <<- EOF
            {
              "conclusion": "success",
              "details_url": "https://details.kenmuse.com",
              "output": {
                "title": "My Check Run Title ðŸš€",
                "summary": "**Summary**: The run completed.",
                "text": "Everything worked as expected. You should see a logo above."
               }
            }
          EOF 