name: Make Experimental Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "generated_src/**"
      - "generated_include/**"
      - "Dependencies/**"
      - "proxy"
      - "proxy_generator"

permissions:
  contents: read

jobs:
  make-release:
    permissions: write-all
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # needed to get commits since last tag
          ssh-key: ${{ secrets.UEPSEUDO_SSH_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Setup DirectX SDK (for xinput1_3.dll)
        run: |
          Invoke-WebRequest -URI https://download.microsoft.com/download/1/7/1/1718CCC4-6315-4D8E-9543-8E28A4E18C4C/dxwebsetup.exe -OutFile dxwebsetup.exe
          Start-Process -Wait dxwebsetup.exe /q

      - name: Build
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Package
        run: python tools/buildscripts/build.py package -e

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: experimental
          body_path: release/release_notes.md
          files: |
            release/UE4SS_v*.zip
            release/zDEV-UE4SS_v*.zip
            release/zCustomGameConfigs.zip
            release/zMapGenBP.zip
