name: Make Experimental Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "UE4SS/src/**"
      - "UE4SS/include/**"
      - "UE4SS/generated_src/**"
      - "UE4SS/generated_include/**"
      - "deps/**"
      - "UE4SS/proxy_generator/**"

permissions:
  contents: read

jobs:
  make-release:
    permissions: write-all
    runs-on: windows-2022

    steps:
      - name: Setup github SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.UEPSEUDO_SSH_KEY }}
          known_hosts: unnecessary

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # needed to get commits since last tag
          ssh-key: ${{ secrets.UEPSEUDO_SSH_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Build
        run: |
          xmake f -m "Game__Shipping__Win64"
          xmake build

      - name: Package
        run: python tools/buildscripts/build.py package -e

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: experimental
          body_path: release/release_notes.md
          files: |
            release/UE4SS_v*.zip
            release/zDEV-UE4SS_v*.zip
            release/zCustomGameConfigs.zip
            release/zMapGenBP.zip
